sudo: required

env:
  - VERSION=1.4.3 TAG=latest

services:
   - docker

script:
   - ./build.sh -t $TAG -v $VERSION build


before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: ./build.sh -t $TAG -v $VERSION deploy

