
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-region
spec:
  serviceName: hbase-region
  replicas: 3
  selector:
    matchLabels:
      app: hbase
      component: region
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hbase
        component: region
    spec:
      containers:
      - name: hbase-region
        image: flokkr/hbase:2.2.4
        args:
        - hbase
        - regionserver
        - start
        volumeMounts:
        - name: data
          mountPath: /data
        - name: mount
          mountPath: /opt/smoketest
        envFrom:
        - configMapRef:
            name: hbase-config
        - configMapRef:
            name: hdfs-config
      volumes:
      - name: config
        configMap:
          name: hbase-config
      - name: data
        emptyDir: {}
      - name: mount
        hostPath:
          path: /home/elek/projects/flokkr/docker-hbase/examples/smoketest
