
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
spec:
  serviceName: hdfs-datanode
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: hdfs
      component: datanode
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hdfs
        component: datanode
    spec:
      containers:
      - name: hdfs-datanode
        image: flokkr/hadoop:3.2.1
        args:
        - hdfs
        - datanode
        env:
        - name: WAITFOR
          value: hdfs-namenode-0.hdfs-namenode:9820
        volumeMounts:
        - name: data
          mountPath: /data
        - name: mount
          mountPath: /opt/smoketest
        envFrom:
        - configMapRef:
            name: hdfs-config
      volumes:
      - name: config
        configMap:
          name: hdfs-config
      - name: data
        emptyDir: {}
      - name: mount
        hostPath:
          path: /home/elek/projects/flokkr/docker-hbase/examples/smoketest
