apiVersion: v1
kind: Service
metadata:
  name: hbase-master
spec:
  ports:
  - port: 16010
    name: web
  clusterIP: None
  selector:
     app: hbase
     component: master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
spec:
  serviceName: hbase-master
  replicas: 1
  selector:
     matchLabels:
        app: hbase
        component: master
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hbase
        component: master
    spec:
      containers:
        - name: hbase-master
          image: flokkr/hbase:2.2.4
          args: ["hbase","master","start"]
          env:
              - name: WAITFOR
                value: "hdfs-namenode-0.hdfs-namenode:9820"
          volumeMounts:
          - name: data
            mountPath: /data
          envFrom:
             - configMapRef:
                  name: hbase-config
      volumes:
        - name: config
          configMap:
            name: hbase-config
        - name: data
          emptyDir: {}
