apiVersion: v1
kind: Service
metadata:
  name: hbase-region
spec:
  ports:
  - port: 16030
    name: web
  clusterIP: None
  selector:
     app: hbase
     component: region
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-region
spec:
  serviceName: hbase-region
  replicas: 3
  selector:
     matchLabels:
        app: hbase
        component: region
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hbase
        component: region
    spec:
      containers:
        - name: hbase-region
          image: flokkr/hbase
          args: ["hbase","regionserver","start"]
          volumeMounts:
          - name: data
            mountPath: /data
          envFrom:
             - configMapRef:
                  name: hbase-config
      volumes:
        - name: config
          configMap:
            name: hbase-config
        - name: data
          emptyDir: {}
